# SITE CONFIGURATION
title: Tempelrejo # your site title
author: GitHub User # You :P
description: > # Meta description of Homepage
  Website menampilkan katalog UMKM yang ada di desa Tempelrejo dan Profil Desa Tempelrejo
baseurl: "/" # the subpath of your site, e.g. /blog
kelompok: KKN-R Tim 118 Universitas Diponegoro

url: "https://tempelrejo.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Tempelrejo
  links:
    - https://github.com/tempelrejo

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'Profil Desa', link: '/profil-desa'}
  - {name: 'Demografi', link: '/demografi'}
  - {name: 'Kontak', link: '/kontak'}

tagline: >
  Mondokan, Sragen, Jawa Tengah

# hero_img: posts/sleek_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg
hero_img: posts/TempelrejoC.jpeg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: your-email@domain.com # email for form submission

# twitter_username:  # replace with your_twitter_username or comment to remove link from footer
github_username:  Tempelrejo # replace with your_github_username or comment to remove link from footer
# instagram_username:  # replace with your_instagram_username or comment to remove link from footer

# disqus:
  # shortname: janczizikow # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
